### PR TITLE
ZWEB-3674 JF Make All Library Packages Fixed & Fix Security Issues

### PR DESCRIPTION
**Pull request by Jacob-Friesen**
**Replication**
1. Run the install and audit: `npm install && npm audit`
1. Run the tests: `npm test`
1. Confirm that all the gulp tasks still run

Note a lot of unneeded functionality like karma PhantomJS or automatic JS file wrapping is no longer needed, so it was removed.

### CODE REVIEW

**Comment by Jacob-Friesen** [comment]
@etelmon I have decided to review that open branch and get it merged. So you have some minor changes to address:  https://github.com/z-open/zerv-ng-core/pull/10#pullrequestreview-412738854. Once that is in `develop`, I will integrate those changes into here.

BTW, it is best to leave a comment in a PR review to make it easier to respond to.

**Comment by Jacob-Friesen** [comment]
@etelmon That one will be merged in and included here. I just have to fix the conflicts.

**Comment by etelmon** [comment]
Npm audit shows a high vulnerability.   (I did delete my node_modules before npm install)

**Comment by Jacob-Friesen** [comment]
@etelmon That is probably the new Karma one. It just started occurring yesterday. There is a lot of activity on this. So it should be dealt with soon. Until that is done, we should hold off on merging this one though.

**Comment by etelmon** [comment]
There is still high vulnerability: but switching to    "karma": "5.0.8" seems to fix it.

**Comment by etelmon** [comment]
and the version should not be 1.1.8 (release missing)

**Comment by Jacob-Friesen** [comment]
@etelmon I upgraded the package.json main version. Updating Karma with the very recent 5.0.8 release is not necessary but might as well be done now since there is already a PR out. Karma uses an unlocked `http-proxy` sub dependency, which is why `5.0.5` or any `5.x` version will included the new update immediately.

**Pull request merged**
